/* emit.c - C emission for the recompiler. See emit.h.
 *
 * emit_functions() is the real translator: one readable C function per
 * discovered basic block, each instruction annotated with its address +
 * disassembly and lowered to an vic20recomp runtime helper call (recomp_rt.h).
 * Every inter-block transfer (branch, JMP, JSR, RTS, fall-through) sets the PC
 * and returns to the host driver, which dispatches the next block - so control
 * flow is never a nested C call and a never-returning loop can't overflow the
 * C stack. A target that isn't a recompiled block is interpreted by the host. */
#include "emit.h"
#include "decode.h"
#include "a2regs.h"
#include <stdio.h>
#include <string.h>

static int write_file(const char *path, const char *contents) {
    FILE *f = fopen(path, "wb");
    if (!f) return -1;
    fputs(contents, f);
    fclose(f);
    return 0;
}

int emit_skeleton(const char *outdir, const char *rom_label) {
    char path[1024];
    char buf[4096];

    snprintf(path, sizeof(path), "%s/recomp_funcs.h", outdir);
    snprintf(buf, sizeof(buf),
        "/* recomp_funcs.h - generated by m6502recomp (skeleton placeholder).\n"
        " * Source: %s\n"
        " * Regenerate from your own image with `m6502recomp recompbin`. */\n"
        "#ifndef RECOMP_FUNCS_H\n#define RECOMP_FUNCS_H\n"
        "#include \"vic20recomp/recomp_rt.h\"\n"
        "void vic_recomp_register(void);\n#endif\n",
        rom_label ? rom_label : "(unknown)");
    if (write_file(path, buf) != 0) return -1;

    snprintf(path, sizeof(path), "%s/recomp_funcs.c", outdir);
    snprintf(buf, sizeof(buf),
        "/* recomp_funcs.c - generated by m6502recomp (skeleton placeholder).\n"
        " * Source: %s\n * No functions yet - regenerate with recompbin. */\n"
        "#include \"recomp_funcs.h\"\n"
        "void vic_recomp_register(void) { }\n",
        rom_label ? rom_label : "(unknown)");
    return write_file(path, buf);
}

/* ---- real emitter ---- */

/* Absolute base address: the literal operand, unless the instruction's operand
 * bytes are self-modified, in which case it's read from memory at run time. */
static void abs_base(const insn_t *in, char *out, int n) {
    if (analyze_patched[(uint16_t)(in->pc + 1)] || analyze_patched[(uint16_t)(in->pc + 2)])
        snprintf(out, n, "(uint16_t)(vic_mem_read(0x%04X) | (vic_mem_read(0x%04X) << 8))",
                 (uint16_t)(in->pc + 1), (uint16_t)(in->pc + 2));
    else
        snprintf(out, n, "0x%04X", in->operand);
}

/* Effective-address C expression for the addressing modes that touch memory. */
static void addr_expr(const insn_t *in, char *out, int n) {
    char b[160];
    switch (in->mode) {
        case AM_ZP:  snprintf(out, n, "0x%02X", in->operand); break;
        case AM_ZPX: snprintf(out, n, "(uint8_t)(0x%02X + vic_cpu.x)", in->operand); break;
        case AM_ZPY: snprintf(out, n, "(uint8_t)(0x%02X + vic_cpu.y)", in->operand); break;
        case AM_ABS: abs_base(in, out, n); break;
        case AM_ABX: abs_base(in, b, sizeof(b)); snprintf(out, n, "(uint16_t)(%s + vic_cpu.x)", b); break;
        case AM_ABY: abs_base(in, b, sizeof(b)); snprintf(out, n, "(uint16_t)(%s + vic_cpu.y)", b); break;
        case AM_IZX: snprintf(out, n, "vic_zp_ptr((uint8_t)(0x%02X + vic_cpu.x))", in->operand); break;
        case AM_IZY: snprintf(out, n, "(uint16_t)(vic_zp_ptr(0x%02X) + vic_cpu.y)", in->operand); break;
        default:     snprintf(out, n, "0 /*?*/"); break;
    }
}
/* Read-value C expression (immediate literal, or a memory read). */
static void rd_expr(const insn_t *in, char *out, int n) {
    if (in->mode == AM_IMM) { snprintf(out, n, "0x%02X", in->operand); return; }
    char a[200]; addr_expr(in, a, sizeof(a));
    snprintf(out, n, "vic_mem_read(%s)", a);
}

static const char *branch_cond(const char *m) {
    if (!strcmp(m,"BPL")) return "!vic_cpu.n";
    if (!strcmp(m,"BMI")) return "vic_cpu.n";
    if (!strcmp(m,"BVC")) return "!vic_cpu.v";
    if (!strcmp(m,"BVS")) return "vic_cpu.v";
    if (!strcmp(m,"BCC")) return "!vic_cpu.c";
    if (!strcmp(m,"BCS")) return "vic_cpu.c";
    if (!strcmp(m,"BNE")) return "!vic_cpu.z";
    if (!strcmp(m,"BEQ")) return "vic_cpu.z";
    return NULL;
}

/* If this instruction names an VIC-20 soft switch or ROM entry, return
 * " ; NAME (note)" to append to the line comment, else "". */
static const char *reg_annot(const insn_t *in) {
    static char s[80];
    if (in->mode != AM_ABS && in->mode != AM_ABX && in->mode != AM_ABY &&
        in->mode != AM_IND)
        return "";
    const char *name = vic_reg_name((uint16_t)in->operand);
    if (!name) return "";
    const char *note = vic_reg_note((uint16_t)in->operand);
    if (note) snprintf(s, sizeof(s), " ; %s (%s)", name, note);
    else      snprintf(s, sizeof(s), " ; %s", name);
    return s;
}

/* Emit the C body for one instruction (no leading comment). */
static void emit_insn(FILE *f, const insn_t *in) {
    const char *m = in->mnemonic;
    char a[200], v[256];

    /* simple register / flag ops first */
    if (!strcmp(m,"NOP")) { fprintf(f, "; /* nop */"); return; }
    if (!strcmp(m,"CLC")) { fprintf(f, "vic_cpu.c = 0;"); return; }
    if (!strcmp(m,"SEC")) { fprintf(f, "vic_cpu.c = 1;"); return; }
    if (!strcmp(m,"CLI")) { fprintf(f, "vic_cpu.i = 0;"); return; }
    if (!strcmp(m,"SEI")) { fprintf(f, "vic_cpu.i = 1;"); return; }
    if (!strcmp(m,"CLD")) { fprintf(f, "vic_cpu.d = 0;"); return; }
    if (!strcmp(m,"SED")) { fprintf(f, "vic_cpu.d = 1;"); return; }
    if (!strcmp(m,"CLV")) { fprintf(f, "vic_cpu.v = 0;"); return; }
    if (!strcmp(m,"INX")) { fprintf(f, "vic_inx();"); return; }
    if (!strcmp(m,"INY")) { fprintf(f, "vic_iny();"); return; }
    if (!strcmp(m,"DEX")) { fprintf(f, "vic_dex();"); return; }
    if (!strcmp(m,"DEY")) { fprintf(f, "vic_dey();"); return; }
    if (!strcmp(m,"TAX")) { fprintf(f, "vic_tax();"); return; }
    if (!strcmp(m,"TAY")) { fprintf(f, "vic_tay();"); return; }
    if (!strcmp(m,"TXA")) { fprintf(f, "vic_txa();"); return; }
    if (!strcmp(m,"TYA")) { fprintf(f, "vic_tya();"); return; }
    if (!strcmp(m,"TSX")) { fprintf(f, "vic_tsx();"); return; }
    if (!strcmp(m,"TXS")) { fprintf(f, "vic_txs();"); return; }
    if (!strcmp(m,"PHA")) { fprintf(f, "vic_pha();"); return; }
    if (!strcmp(m,"PHP")) { fprintf(f, "vic_php();"); return; }
    if (!strcmp(m,"PLA")) { fprintf(f, "vic_pla();"); return; }
    if (!strcmp(m,"PLP")) { fprintf(f, "vic_plp();"); return; }

    /* loads / stores / logical / arithmetic on a value */
    if (!strcmp(m,"LDA")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_lda(%s);", v); return; }
    if (!strcmp(m,"LDX")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_ldx(%s);", v); return; }
    if (!strcmp(m,"LDY")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_ldy(%s);", v); return; }
    if (!strcmp(m,"ORA")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_ora(%s);", v); return; }
    if (!strcmp(m,"AND")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_and(%s);", v); return; }
    if (!strcmp(m,"EOR")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_eor(%s);", v); return; }
    if (!strcmp(m,"ADC")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_adc(%s);", v); return; }
    if (!strcmp(m,"SBC")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_sbc(%s);", v); return; }
    if (!strcmp(m,"CMP")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_cmp(%s);", v); return; }
    if (!strcmp(m,"CPX")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_cpx(%s);", v); return; }
    if (!strcmp(m,"CPY")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_cpy(%s);", v); return; }
    if (!strcmp(m,"BIT")) { rd_expr(in,v,sizeof(v)); fprintf(f, "vic_bit(%s);", v); return; }
    if (!strcmp(m,"STA")) { addr_expr(in,a,sizeof(a)); fprintf(f, "vic_mem_write(%s, vic_cpu.a);", a); return; }
    if (!strcmp(m,"STX")) { addr_expr(in,a,sizeof(a)); fprintf(f, "vic_mem_write(%s, vic_cpu.x);", a); return; }
    if (!strcmp(m,"STY")) { addr_expr(in,a,sizeof(a)); fprintf(f, "vic_mem_write(%s, vic_cpu.y);", a); return; }

    /* read-modify-write / shifts (A or memory) */
    if (!strcmp(m,"INC") || !strcmp(m,"DEC") || !strcmp(m,"ASL") ||
        !strcmp(m,"LSR") || !strcmp(m,"ROL") || !strcmp(m,"ROR")) {
        const char *op =
            !strcmp(m,"INC") ? "vic_alu_inc" : !strcmp(m,"DEC") ? "vic_alu_dec" :
            !strcmp(m,"ASL") ? "vic_alu_asl" : !strcmp(m,"LSR") ? "vic_alu_lsr" :
            !strcmp(m,"ROL") ? "vic_alu_rol" : "vic_alu_ror";
        if (in->mode == AM_ACC) {
            fprintf(f, "vic_cpu.a = %s(vic_cpu.a);", op);
        } else {
            addr_expr(in,a,sizeof(a));
            fprintf(f, "{ uint16_t _ea = %s; vic_mem_write(_ea, %s(vic_mem_read(_ea))); }", a, op);
        }
        return;
    }

    /* conditional branches: take the branch or fall through, both dispatched
     * through the host driver (the target and the fall-through are both block
     * leaders, so a cycle ping-pongs through the driver, never recursing). */
    {
        const char *cond = branch_cond(m);
        if (cond) {
            uint16_t nxt = (uint16_t)(in->pc + in->len);
            fprintf(f, "if (%s) { vic_cpu.pc = 0x%04X; return; } vic_cpu.pc = 0x%04X; return;",
                    cond, in->target, nxt);
            return;
        }
    }

    /* unconditional control transfer: set the PC and return to the driver. */
    if (!strcmp(m,"JMP")) {
        /* NMOS JMP ($xxFF) reads the high byte from $xx00 - the page-wrap bug,
         * modeled in vic_mem_read16_bug. */
        if (in->mode == AM_IND) fprintf(f, "vic_cpu.pc = vic_mem_read16_bug(0x%04X); return;", in->operand);
        else                    fprintf(f, "vic_cpu.pc = 0x%04X; return;", in->target);
        return;
    }
    if (!strcmp(m,"JSR")) {
        /* Push the 6502 return address (pc+2; RTS pops +1) so SP tracking and
         * the RTS-trick stay correct, then dispatch the target via the driver.
         * The return address is its own block, dispatched when the callee RTSs. */
        fprintf(f, "vic_push16(0x%04X); vic_cpu.pc = 0x%04X; return;",
                (uint16_t)(in->pc + 2), in->target);
        return;
    }
    if (!strcmp(m,"RTS")) { fprintf(f, "vic_rts_ret(); return;"); return; }
    if (!strcmp(m,"RTI")) { fprintf(f, "vic_rti(); return;"); return; }
    if (!strcmp(m,"BRK")) { fprintf(f, "vic_unimpl(0x00); return; /* BRK */"); return; }
    if (!strcmp(m,"JAM")) { fprintf(f, "vic_unimpl(0x%02X); return; /* JAM */", in->opcode); return; }

    /* undocumented opcodes and anything else: route to the runtime hook. */
    fprintf(f, "vic_unimpl(0x%02X); /* %s%s */", in->opcode, m, in->undoc ? " (undoc)" : " unhandled");
}

int emit_functions(const char *outdir, const uint8_t *rom, size_t rom_size,
                   uint16_t base, const func_table_t *t, const char *rom_label) {
    char path[1024];

    /* header: prototypes */
    snprintf(path, sizeof(path), "%s/recomp_funcs.h", outdir);
    FILE *h = fopen(path, "wb");
    if (!h) return -1;
    fprintf(h,
        "/* recomp_funcs.h - generated by m6502recomp.\n"
        " * Source: %s\n"
        " * %d functions discovered. Do not edit by hand. */\n"
        "#ifndef RECOMP_FUNCS_H\n#define RECOMP_FUNCS_H\n"
        "#include \"vic20recomp/recomp_rt.h\"\n\n",
        rom_label ? rom_label : "(unknown)", t->nfuncs);
    for (int i = 0; i < t->nfuncs; i++)
        if (!t->funcs[i].self_mod)
            fprintf(h, "void vic_func_%04X(void);\n", t->funcs[i].start);
    fprintf(h, "\n/* Register every recompiled function in the dispatch table so\n"
               " * computed jumps and the IRQ/reset vectors can reach them. */\n"
               "void vic_recomp_register(void);\n");
    fprintf(h, "\n#endif\n");
    fclose(h);

    /* body */
    snprintf(path, sizeof(path), "%s/recomp_funcs.c", outdir);
    FILE *f = fopen(path, "wb");
    if (!f) return -1;
    fprintf(f,
        "/* recomp_funcs.c - generated by m6502recomp.\n"
        " * Source: %s    Functions: %d\n"
        " *\n"
        " * This is a STATIC RECOMPILATION: every 6502 routine the analyzer\n"
        " * reached becomes one C function `vic_func_XXXX`, where XXXX is its\n"
        " * start address. The original machine code is not interpreted at run\n"
        " * time - it was translated to the C below ahead of time.\n"
        " *\n"
        " * How to read a function. Each translated line looks like:\n"
        " *       [comment: AAAA: MNEMONIC OPERAND ; REG (note)]  C statement\n"
        " *   - AAAA is the instruction's address in the original image.\n"
        " *   - The text after it is the disassembly of that instruction.\n"
        " *   - ` ; REG (note)` appears when the operand is an VIC-20 soft\n"
        " *     switch or ROM entry, e.g. `STA $C030 ; SPKR (toggle speaker)`.\n"
        " *   - The C statement is the translation. CPU state lives in the\n"
        " *     `vic_cpu` struct; `vic_<op>()` helpers (recomp_rt.h) perform the\n"
        " *     operation AND set N/Z/C/V exactly as the real op would.\n"
        " *\n"
        " * Control flow - every routine is carved into basic blocks, one C\n"
        " * function `vic_func_AAAA` each, and every inter-block transfer is\n"
        " * dispatched through the host driver rather than a nested C call:\n"
        " *   - A branch/JMP/fall-through sets `vic_cpu.pc` and returns; the host\n"
        " *     loop dispatches the next block. A never-returning game loop thus\n"
        " *     ping-pongs through the driver instead of recursing in C.\n"
        " *   - JSR pushes the return address (for SP tracking and the RTS-trick)\n"
        " *     then dispatches the target; RTS pops it back into the PC.\n"
        " *   - A computed/indirect or out-of-image target is just a PC value:\n"
        " *     the driver runs it if recompiled, else interprets it.\n"
        " *\n"
        " * Do not edit by hand - regenerate with `m6502recomp recompbin`. */\n"
        "#include \"recomp_funcs.h\"\n\n",
        rom_label ? rom_label : "(unknown)", t->nfuncs);

    for (int i = 0; i < t->nfuncs; i++) {
        const func_t *fn = &t->funcs[i];
        if (fn->self_mod) continue;   /* self-modifying: left interpreted */
        fprintf(f, "/* vic_func_%04X: $%04X-$%04X (%d bytes)%s */\n",
                fn->start, fn->start, (uint16_t)(fn->end - 1), fn->end - fn->start,
                fn->reaches_ret ? "" : fn->fallthrough ? ", falls through" : "");
        fprintf(f, "void vic_func_%04X(void) {\n", fn->start);

        uint16_t addr = fn->start;
        int lastcf = CF_NORMAL;
        while (addr < fn->end) {
            size_t off = (size_t)(addr - base);
            uint8_t tmp[3] = {0,0,0};
            size_t avail = rom_size - off;
            tmp[0] = rom[off];
            if (avail > 1) tmp[1] = rom[off+1];
            if (avail > 2) tmp[2] = rom[off+2];

            insn_t in;
            m6502_decode(tmp, addr, &in);
            if (in.len > avail) break;

            char dis[48];
            m6502_format(&in, dis, sizeof(dis));
            fprintf(f, "    /* %04X: %-18s%s */ ", addr, dis, reg_annot(&in));
            emit_insn(f, &in);
            fprintf(f, "\n");

            lastcf = in.cflow;
            addr = (uint16_t)(addr + in.len);
        }
        /* A block split at an interior leader (or that ran to the image edge)
         * ends with no control-flow terminator: continue to the next block. */
        if (lastcf == CF_NORMAL)
            fprintf(f, "    vic_cpu.pc = 0x%04X; return;\n", fn->end);
        fprintf(f, "}\n\n");
    }

    /* dispatch registration (self-modifying functions are intentionally not
     * registered, so the runtime interprets them) */
    int n_sm = 0; for (int i = 0; i < t->nfuncs; i++) n_sm += t->funcs[i].self_mod;
    fprintf(f, "/* %d of %d functions are self-modifying and left interpreted. */\n",
            n_sm, t->nfuncs);
    for (int i = 0; i < t->nfuncs; i++)
        if (t->funcs[i].self_mod)
            fprintf(stderr, "  self-modifying block: $%04X-$%04X\n",
                    t->funcs[i].start, (uint16_t)(t->funcs[i].end - 1));
    fprintf(f, "void vic_recomp_register(void) {\n");
    for (int i = 0; i < t->nfuncs; i++)
        if (!t->funcs[i].self_mod)
            fprintf(f, "    vic_register(0x%04X, vic_func_%04X);\n",
                    t->funcs[i].start, t->funcs[i].start);
    fprintf(f, "}\n");
    fclose(f);
    return 0;
}
